### ISSUE TITLE
stax add command template includes let

### ISSUE THREAD

**Issue by talentedmrjones** [cue-sh/stax#10]
Current default template contents is missing the let keyword in `stack=`

**Comment by jlongtine** [comment]
@talentedmrjones I think a better way to do this for the future will be `Value aliases`, as described here: https://github.com/cuelang/cue/releases/tag/v0.4.0-beta.1

**Comment by jlongtine** [comment]
So, instead of `stack=Stacks[StackName]`, we'll do `Stacks: ReallyInterestingStack: stack={...}`

**Comment by talentedmrjones** [comment]
Mmmm, love that sugar!
